name: "Gold Spread to Telegram"

on:
  schedule:
    # Weekdays at 09:00 Europe/Madrid (CEST = UTC+2). 09:00 CEST == 07:00 UTC.
    - cron: "0 6 * * 1-5"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Gold Spread Reporter
        env:
          # SGE source options: XWTEAM (default) or JISU
          SGE_SOURCE: ${{ vars.SGE_SOURCE }}
          # If you choose JISU, provide the key via secret below
          JISUAPI_KEY: ${{ secrets.JISUAPI_KEY }}
          # Choose which SGE field to use: SP | BP | MID (avg of SP & BP)
          SGE_PRICE_MODE: ${{ vars.SGE_PRICE_MODE }}

          # FX source options: TRADINGVIEW (default), EXCHANGERATE_HOST, or YAHOO
          FX_SOURCE: ${{ vars.FX_SOURCE }}
          # Optional: override TradingView FX ticker (default: FX_IDC:USDCNY)
          TV_FX_TICKER: ${{ vars.TV_FX_TICKER }}

          # --- Reference gold (Step 4) ---
          # Choose reference source: FUTURES (default) or TV_SPOT
          REF_SOURCE: ${{ vars.REF_SOURCE }}
          # When REF_SOURCE=TV_SPOT, set the TradingView spot ticker (default: OANDA:XAUUSD)
          TV_SPOT_TICKER: ${{ vars.TV_SPOT_TICKER }}
          # FUTURES options (kept for backward compatibility)
          YF_FUT_SYMBOL: ${{ vars.YF_FUT_SYMBOL }}
          TV_FUT_TICKER: ${{ vars.TV_FUT_TICKER }}

          # Optional: specify parse mode for Telegram: 'HTML' or 'Markdown'
          TELEGRAM_PARSE_MODE: ${{ vars.TELEGRAM_PARSE_MODE }}
          # Required secrets for Telegram
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python src/report.py
