name: "Gold Spread to Telegram"

on:
  schedule:
    # Weekdays at 09:00 Europe/Madrid (CEST = UTC+2). 09:00 CEST == 07:00 UTC.
    - cron: "0 7 * * 1-5"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Gold Spread Reporter
        env:
          SGE_SOURCE: ${{ vars.SGE_SOURCE }}
          JISUAPI_KEY: ${{ secrets.JISUAPI_KEY }}
          SGE_PRICE_MODE: ${{ vars.SGE_PRICE_MODE }}
          FX_SOURCE: ${{ vars.FX_SOURCE }}
          TV_FX_TICKER: ${{ vars.TV_FX_TICKER }}
          YF_FUT_SYMBOL: ${{ vars.YF_FUT_SYMBOL }}
          TELEGRAM_PARSE_MODE: ${{ vars.TELEGRAM_PARSE_MODE }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python src/report.py
